### ISSUE TITLE
Client secret is required again

### ISSUE THREAD

**Issue by graemechapman** [mnao305/chrome-extension-upload#13]
It would appear that client secrets are needed again due to changes in Google's oauth flow. See https://github.com/fregante/chrome-webstore-upload/issues/59 for further context. As this action uses chrome-webstore-upload it looks like this will need to be updated to the latest version and the client secret re-implemented to avoid getting a 400 when uploading the extension.

**Comment by mnao305** [comment]
Thanks!
I will fix it this weekend, but PRs are welcome.

**Comment by orestes** [comment]
You got it @mnao305 :D

**Comment by orestes** [comment]
Bad news, this wasn't enough.  See my test build https://github.com/orestes/extension-news-blocker/runs/7263364316?check_suite_focus=true

I checked and it seems like [we're using chrome-webstore-upload@1.0.0](https://github.com/mnao305/chrome-extension-upload/blob/master/package.json#L29)  which is the latest version from [fregante/chrome-webstore-upload](https://github.com/fregante/chrome-webstore-upload/blob/main/package.json#L3) and is meant to be fixed after https://github.com/fregante/chrome-webstore-upload/issues/59

Was anyone successful trying this update? I'd love some hints on how to debug this.

**Comment by mnao305** [comment]
@orestes 
Oh, I forgot to build and push under the dist directory... my bad...

We have re-released it.
https://github.com/mnao305/chrome-extension-upload/releases/tag/3.0.0

**Comment by orestes** [comment]
Awesome! I can confirm the workflow is working fine. Thanks for re-releasing! I'd say it's safe to close this issue now :)
