### ISSUE TITLE
HTTPError: Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by Toumash** [mnao305/chrome-extension-upload#17]
Hi,
thanks one more time for the best project on github for uploading packages to chrome web store!

I've been using this action for 1,5-2 years. And recently 28.09.2022 i've switched to the new OAuth with secret (back again i know). It worked fine - last successfull deploy is from 4.10.2022. After that date all i've got is:

> upload error - You will need to go to the Chrome Web Store Developer Dashboard and upload it manually.

Am i the only one?

What should i do?
Uploading it manually works just fine.

**Comment by mnao305** [comment]
Hmmm, I can upload the file without any problem in my environment.

Try regenerating the `client-id` and `secret-token` and give it a try.
Maybe those API Keys are disabled.

(I use DeepL.)

**Comment by Toumash** [comment]
Regenerated them, works fine. Closing.
The app was in testing phase, not published cause i've seen that it is possible to use it apparently in some tutorial :x
