### ISSUE TITLE
Deprecated Node 12 actions

### ISSUE THREAD

**Issue by simoneb** [mnao305/chrome-extension-upload#18]
Node 12 actions are deprecated, can you please update the action so that it uses a more recent version?

See  https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12

When using this action in a workflow, you'll now get a warning, see https://github.com/nearform/github-snooze-chrome-extension/actions/runs/3638038554

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: mnao305/chrome-extension-upload@3.0.0

**Comment by mnao305** [comment]
OK. Version 4.0.0 has been released.
https://github.com/mnao305/chrome-extension-upload/releases/tag/v4.0.0

**Comment by simoneb** [comment]
Thanks for this change! Note that you changed the versioning scheme from 3.0.0 to v4.0.0.

Another thing you may consider is using the tagging approach recommended in the docs. When you release version v4.0.0, you create tags:

- v4.0.0
- v4.0
- v4

All of them point to the same commit so that people can reference either of those. When you release e.g. version v4.0.1:

- you create a new tag v4.0.1
- keep v4.0 unchanged
- move tag v4 to point to the same commit as v4.0.1

In our repos, we are automating this process using https://github.com/nearform/optic-release-automation-action, but there are alternatives such as Google's https://github.com/googleapis/release-please (which I believe can do this too).

**Comment by inson1** [comment]
@mnao305 I think you should also update Readme :)
