### ISSUE TITLE
Deprecated Node 16 actions

### ISSUE THREAD

**Issue by danielhjacobs** [mnao305/chrome-extension-upload#25]
Just like #18, Node 16 is now deprecated (https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) and this action gives a warning.

**Comment by mnao305** [comment]
Thanks for letting me know.

Version v5.0.0 has been released.
https://github.com/mnao305/chrome-extension-upload/releases/tag/v5.0.0
