### ISSUE TITLE
Is client_secret really required?

### ISSUE THREAD

**Issue by Toumash** [mnao305/chrome-extension-upload#7]
The [article that you are referring to](https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md) from [the marketplace](https://github.com/marketplace/actions/chrome-extension-upload-action) states that `client_secret` is not really needed for the google api, but my github action keeps failing with client_secret not provided

**Comment by Toumash** [comment]
I could be really easily resolved by removing the `client_secret` arg and updating the libaray to the newest version (0.6 as opposed to 0.2)

**Comment by mnao305** [comment]
@Toumash 
Thanks for letting me know about this!
It certainly looks like I don't need to use `client_secret` anymore now.

I'll try to fix it so that it doesn't use `client_secret` (pull requests are welcome, of course).

(I use DeepL)

**Comment by Toumash** [comment]
I would love to provide PR, but im not sure how to test github actions without actually running them

**Comment by mnao305** [comment]
@Toumash Thanks!

Sorry, I don't know how to test this completely locally. (I did not create a test file. Sorry.)

If you have created (or forked) an action, you should use it in the following format.
```
- uses: <username>/tchrome-extension-upload@master
```
This should work without having to publish it to Marketplace. You can try it with this.


(I use DeepL)

**Comment by Toumash** [comment]
I've got at problem when running my updated version  `Error: __webpack_require__(...) is not a function`. How to compile it? Im using node  12.22.7 and ran npm run all after making the change
branch: https://github.com/Toumash/chrome-extension-upload/tree/feature/client-secret-not-required-anymore

**Comment by mnao305** [comment]
Hmm, just run `npm run all` and the build should be complete.

**Comment by mnao305** [comment]
@Toumash 
Hello!

I looked at the changelog of the library used, and it says that it was rewritten to pure ESM. I think this is probably related to the problem.
https://github.com/fregante/chrome-webstore-upload/releases

Is it possible to rewrite it with reference to the current README? or use v0.5.0.
https://github.com/fregante/chrome-webstore-upload#create-a-new-client

It is currently using `require`, so changing it to `import` should solve the problem.

(I use DeepL)

**Comment by huynv86** [comment]
please update Readme
i want to try this but i don't know client_secret is really need or not

**Comment by mnao305** [comment]
It has been released as Version 2.0.0!
https://github.com/mnao305/chrome-extension-upload/releases/tag/2.0.0
